Roll back version of Roaster
... because 2.23.0.Final fails the build with:
```
java.lang.UnsupportedClassVersionError: org/jboss/forge/roaster/_shade/org/eclipse/jface/text/Document has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.jboss.forge.roaster.spi.JavaParserImpl.parseUnit(JavaParserImpl.java:58)
```